const { getProfile } = require('./profile-store');
const { SKILL_ALIASES } = require('./resume-parser');
const normalise = value => String(value || '').toLowerCase().replace(/[^a-z0-9+#./ -]/g, ' ').replace(/\s+/g, ' ').trim();
const jobText = job => normalise(`${job.title} ${job.description} ${job.location} ${job.region} ${job.salary}`);
const seniorityOf = value => (normalise(value).match(/intern|junior|mid|senior|staff|principal|lead|manager|director/) || [''])[0];
const escape = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const hasTerm = (text, term) => { const needle = normalise(term); return needle && new RegExp(`(^|[^a-z0-9.])${escape(needle)}($|[^a-z0-9.])`).test(text); };
const skillTerms = profile => [...new Set([...(profile.skills || []), ...(profile.keywords || [])])];
function jobSkills(job, profile) { const text = jobText(job); return [...new Set([...skillTerms(profile), ...Object.keys(SKILL_ALIASES)])].filter(skill => hasTerm(text, skill) || (SKILL_ALIASES[skill] || []).some(alias => hasTerm(text, alias))); }
function hasSkill(profile, skill) { const owned = skillTerms(profile).map(normalise); return owned.includes(normalise(skill)) || (SKILL_ALIASES[skill] || []).some(alias => owned.includes(normalise(alias))); }
function matchesRole(job, profile) { const title = normalise(job.title); return (profile.roles || []).some(role => { const words = normalise(role).split(' ').filter(word => word.length > 2 && !/senior|junior|staff|lead|principal|engineer|developer|manager/.test(word)); return words.length ? words.every(word => title.includes(word)) : title.includes(normalise(role)); }); }
function matchesEligibility(job, profile) { const where = normalise(`${job.location} ${job.region}`); return (profile.workEligibility || []).some(eligibility => { const value = normalise(eligibility); if (['worldwide', 'global', 'anywhere'].includes(value)) return /worldwide|global|anywhere|remote/.test(where); if (value === 'latin america') return /latin america|latam/.test(where); return hasTerm(where, value); }); }
function optionalFit(job, profile) { const text = jobText(job); const signals = []; if (profile.workMode) signals.push(hasTerm(text, profile.workMode)); if ((profile.jobTypes || []).length) signals.push(profile.jobTypes.some(type => hasTerm(text, type))); if (profile.minSalaryUsdAnnual) signals.push(/\$|usd|salary|compensation/.test(text)); return signals.length ? signals.filter(Boolean).length / signals.length : 1; }
function evaluateJob(job, profile = getProfile()) { const reasons = []; if (!matchesRole(job, profile)) reasons.push('Target role does not match.'); if (!matchesEligibility(job, profile)) reasons.push('Work eligibility or location does not match.'); if ((profile.excludeCompanies || []).some(company => normalise(job.company).includes(normalise(company)))) reasons.push('Company is excluded.'); const eligible = reasons.length === 0; const requirements = jobSkills(job, profile); const matched = requirements.filter(skill => hasSkill(profile, skill)); const missing = requirements.filter(skill => !hasSkill(profile, skill)); const skillScore = requirements.length ? matched.length / requirements.length : 0; const roleScore = matchesRole(job, profile) ? 1 : 0; const seniorityScore = profile.seniority ? Number(seniorityOf(job.title) === seniorityOf(profile.seniority)) : 1; const preferenceScore = optionalFit(job, profile); const score = eligible ? Math.round((skillScore * 55 + roleScore * 25 + seniorityScore * 10 + preferenceScore * 10) * 100) / 100 : 0; const tier = score >= 85 ? 'Excellent' : score >= 70 ? 'Strong' : 'Potential'; return { eligible, reasons, score, tier, matched, missing, breakdown: { skills: Math.round(skillScore * 55), role: Math.round(roleScore * 25), seniority: Math.round(seniorityScore * 10), preferences: Math.round(preferenceScore * 10) } }; }
function scoreJob(job, profile) { return evaluateJob(job, profile); }
function atsAdvice(job, profile) { const result = evaluateJob(job, profile); return { ...result, exact: result.matched.slice(0, 16), gaps: result.missing.slice(0, 12), bullets: ['Mirror job-description terminology only when it truthfully reflects your experience.', 'Lead with relevant, quantified impact from your real work.', 'Never claim a gap as experience unless you can support it.'] }; }
module.exports = { atsAdvice, evaluateJob, matchesEligibility, matchesRole, scoreJob };
