const fs = require('fs');
const path = require('path');
const PROFILE_PATH = process.env.JOB_RADAR_PROFILE_PATH || path.join(__dirname, 'data', 'profile.json');
const DEFAULT = { name: '', location: '', workEligibility: [], roles: [], skills: [], keywords: [], aliases: [], minSalaryUsdAnnual: 0, jobTypes: [], seniority: '', workMode: '', excludeCompanies: [], keepResume: false };
const list = value => Array.isArray(value) ? [...new Set(value.map(String).map(item => item.trim()).filter(Boolean))] : [];
function normaliseProfile(input = {}) { const profile = { ...DEFAULT, ...input }; for (const field of ['workEligibility', 'roles', 'skills', 'keywords', 'jobTypes', 'excludeCompanies']) profile[field] = list(profile[field]); profile.aliases = Array.isArray(profile.aliases) ? profile.aliases : []; profile.minSalaryUsdAnnual = Math.max(0, Number(profile.minSalaryUsdAnnual) || 0); profile.keepResume = Boolean(profile.keepResume); profile.name = String(profile.name || '').trim(); profile.location = String(profile.location || '').trim(); profile.seniority = String(profile.seniority || '').trim(); profile.workMode = String(profile.workMode || '').trim(); return profile; }
function validateProfile(input) { const profile = normaliseProfile(input); const errors = []; if (!profile.roles.length) errors.push('Add at least one target role.'); if (!profile.workEligibility.length) errors.push('Add at least one work eligibility or location.'); return { profile, errors }; }
function getProfile() { try { return normaliseProfile(JSON.parse(fs.readFileSync(PROFILE_PATH, 'utf8'))); } catch { return { ...DEFAULT }; } }
function saveProfile(input) { const { profile, errors } = validateProfile(input); if (errors.length) { const error = new Error(errors.join(' ')); error.status = 422; throw error; } fs.mkdirSync(path.dirname(PROFILE_PATH), { recursive: true }); fs.writeFileSync(PROFILE_PATH, JSON.stringify(profile, null, 2)); return profile; }
module.exports = { DEFAULT, getProfile, normaliseProfile, saveProfile, validateProfile };
