const path = require('path');
const SKILLS=['Swift','SwiftUI','UIKit','Objective-C','Swift Concurrency','Combine','Core Data','SwiftData','XCTest','XCUITest','SPM','Swift Package Manager','CocoaPods','Tuist','Fastlane','GitHub Actions','CI/CD','Firebase','Crashlytics','Datadog','Sentry','Bugsnag','Instruments','MVVM','VIPER','Clean Architecture','Server-Driven UI','SDUI','Design Systems','Modularization','REST','GraphQL','Python','JavaScript','TypeScript','Node.js','React','Kotlin','Java','Go','Ruby','AWS','Docker','Kubernetes','SQL','SQLite','PostgreSQL','LLM','RAG','MCP','Claude Code','Codex','GitHub Copilot','AI Agents','Generative AI','Machine Learning','Technical Leadership','Mentoring','System Design','Observability','Performance Optimization'];
const ROLE_PATTERNS=[['Staff Software Engineer',/staff\s+(software|mobile|ios|android)?\s*engineer/i],['Senior Software Engineer',/senior\s+software\s+engineer/i],['Senior iOS Engineer',/senior\s+(ios|mobile).*engineer|senior\s+ios\s+(developer|engineer)/i],['Staff Mobile Engineer',/staff\s+mobile/i],['Lead Mobile Engineer',/(lead|principal)\s+(mobile|ios)/i],['Software Engineer',/software\s+engineer/i]];
const normalize=s=>String(s||'').replace(/\s+/g,' ').trim();
function inferLocation(text){const m=text.match(/(?:São Paulo|Sao Paulo|Rio de Janeiro|Fortaleza|Brazil|Brasil|Argentina|Mexico|México|Colombia|Chile|Peru|Uruguay|United States|Canada|Portugal|Spain)/i);return m?m[0].replace('Brasil','Brazil'):'Remote';}
function extractSkills(text){const lower=text.toLowerCase();return [...new Set(SKILLS.filter(s=>lower.includes(s.toLowerCase())))];}
function extractRoles(text){const roles=ROLE_PATTERNS.filter(([,re])=>re.test(text)).map(([r])=>r);return roles.length?[...new Set(roles)].slice(0,6):['Senior Software Engineer'];}
function extractName(text){return text.split(/\r?\n/).map(normalize).filter(Boolean).find(x=>x.length>2&&x.length<70&&!/@|https?:|linkedin|github/i.test(x))||'Job Seeker';}
function profileFromText(text,filename='resume.pdf'){const skills=extractSkills(text);return{name:extractName(text),location:inferLocation(text),regions:['Brazil','LATAM','Latin America','Worldwide','Remote'],roles:extractRoles(text),skills,keywords:skills,resumeFile:filename,resumeParsedAt:new Date().toISOString(),resumeText:normalize(text).slice(0,50000)};}
async function parseResume(buffer,filename){const ext=path.extname(filename||'').toLowerCase();if(ext==='.txt'||ext==='.md')return profileFromText(buffer.toString('utf8'),filename);if(ext!=='.pdf')throw new Error('V2 currently supports PDF, TXT and Markdown resumes.');const pdf=require('pdf-parse');const result=await pdf(buffer);if(!result.text||result.text.trim().length<80)throw new Error('Could not extract enough text from this PDF. Use a text-based ATS-friendly PDF.');return profileFromText(result.text,filename);}
module.exports={parseResume,profileFromText,extractSkills};
