const db = require('./db');
const { evaluateJob } = require('./matcher');
const { getProfile } = require('./profile-store');
const UA = 'JobRadar/3.0 (+open-source local job search tool)';
const clean = value => String(value || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
function relevant(job, profile = getProfile()) { return evaluateJob(job, profile).eligible; }
async function fetchJson(url, options = {}) { const response = await fetch(url, { ...options, headers: { 'User-Agent': UA, ...(options.headers || {}) } }); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function remotive() { const profile = getProfile(); const query = profile.roles[0] || profile.skills[0] || 'software engineer'; const data = await fetchJson(`https://remotive.com/api/remote-jobs?search=${encodeURIComponent(query)}`); return (data.jobs || []).map(job => ({ company: job.company_name, title: job.title, location: job.candidate_required_location || 'Remote', region: job.candidate_required_location || 'Remote', source: 'Remotive', posted: (job.publication_date || '').slice(0, 10), salary: job.salary || 'Not disclosed', url: job.url, description: clean(job.description).slice(0, 6000), open: true })); }
async function remoteok() { const data = await fetchJson('https://remoteok.com/api'); return (Array.isArray(data) ? data.slice(1) : []).map(job => ({ company: job.company || 'Unknown', title: job.position || '', location: job.location || 'Remote', region: job.location || 'Remote', source: 'RemoteOK', posted: job.date ? String(job.date).slice(0, 10) : '', salary: job.salary_min || job.salary_max ? `$${job.salary_min || '?'}–$${job.salary_max || '?'} / year` : 'Not disclosed', url: job.url || job.apply_url, description: clean(`${job.description || ''} ${(job.tags || []).join(' ')}`).slice(0, 6000), open: true })); }
async function braveDiscovery() { const key = process.env.BRAVE_SEARCH_API_KEY; if (!key) return []; const profile = getProfile(); const roles = profile.roles.slice(0, 3).map(role => `"${role}"`).join(' OR '); const eligibility = profile.workEligibility.join(' OR ') || 'remote'; const query = `(site:jobs.lever.co OR site:job-boards.greenhouse.io OR site:jobs.ashbyhq.com) (${roles}) (${eligibility} OR remote)`; const data = await fetchJson(`https://api.search.brave.com/res/v1/web/search?q=${encodeURIComponent(query)}&count=20&freshness=pm`, { headers: { 'X-Subscription-Token': key, Accept: 'application/json' } }); return (data.web?.results || []).map(result => ({ company: (result.profile?.long_name || result.meta_url?.hostname || 'Web result').replace('www.', ''), title: result.title || 'Job opportunity', location: eligibility, region: eligibility, source: 'Web/ATS via Brave Search', posted: new Date().toISOString().slice(0, 10), salary: 'Not disclosed', url: result.url, description: result.description || '', open: true })); }
function upsert(job) { const match = evaluateJob(job); if (!job.url || !match.eligible) return false; db.prepare(`INSERT INTO jobs(company,title,location,region,source,posted,salary,url,description,open,match_score,matched_keywords,missing_keywords,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(url) DO UPDATE SET company=excluded.company,title=excluded.title,location=excluded.location,region=excluded.region,source=excluded.source,posted=excluded.posted,salary=excluded.salary,description=excluded.description,open=1,match_score=excluded.match_score,matched_keywords=excluded.matched_keywords,missing_keywords=excluded.missing_keywords,updated_at=CURRENT_TIMESTAMP`).run(job.company, job.title, job.location, job.region, job.source, job.posted, job.salary, job.url, job.description, job.open ? 1 : 0, match.score, JSON.stringify(match.matched), JSON.stringify(match.missing)); return true; }
async function scan() { const id = db.prepare('INSERT INTO scans DEFAULT VALUES').run().lastInsertRowid; const sources = {}; let found = 0; for (const [name, source] of [['Remotive', remotive], ['RemoteOK', remoteok], ['Brave discovery', braveDiscovery]]) { try { const jobs = await source(); sources[name] = { fetched: jobs.length, accepted: 0 }; for (const job of jobs) if (upsert(job)) { found++; sources[name].accepted++; } } catch (error) { sources[name] = { error: error.message }; } } db.prepare('UPDATE scans SET completed_at=CURRENT_TIMESTAMP,found_count=?,source_summary=? WHERE id=?').run(found, JSON.stringify(sources), id); return { found, sources }; }
if (require.main === module) scan().then(result => console.log(JSON.stringify(result, null, 2))).catch(error => { console.error(error); process.exit(1); });
module.exports = { relevant, scan, upsert };
